Changed Default Theme to be the Dark Theme
mathieumack/Game.Penguins pull request #2
Opened 2019-03-29 20:26 UTC by Mrgove10

This would be awesome for the :eyes:

2019-03-29 20:40 UTC, Meavela commented
Mes 👀 approuvent !

2019-04-11 11:18 UTC, mathieumack requested changes

2019-04-11 11:18 UTC, mathieumack commented on Game.Penguins/Game.Penguins/MainWindow.xaml.cs
> +            ResourceLocator.SetColorScheme(Application.Current.Resources, _isDark ? ResourceLocator.LightColorScheme : ResourceLocator.DarkColorScheme);
If you want to define a specific theme by default, why did you use the _isDark field ?

2019-04-11 11:41 UTC, Mrgove10 commented on Game.Penguins/Game.Penguins/MainWindow.xaml.cs
> +            ResourceLocator.SetColorScheme(Application.Current.Resources, _isDark ? ResourceLocator.LightColorScheme : ResourceLocator.DarkColorScheme);
Corrected the file

2019-10-23 11:36 UTC, closed without merging